apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: "2"
  labels:
    app: ws-test
    app.kubernetes.io/component: ws-test
    app.kubernetes.io/instance: ws-test
    app.kubernetes.io/part-of: ws-test-app
  name: ws-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ws-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ws-test
        deploymentconfig: ws-test
    spec:
      containers:
      - env:
        - name: "ENVIRONMENT"
          value: {{ .Values.env }}
        image: "{{ .Values.imagestream }}/ws-test:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: ws-test
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
