apiVersion: v1
kind: Service
metadata:
  labels:
    app: ws-test
    app.kubernetes.io/component: ws-test
    app.kubernetes.io/instance: ws-test
    app.kubernetes.io/part-of: ws-test-app
  name: ws-test
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ws-test
    deploymentconfig: ws-test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
